### ISSUE TITLE
Bei Magic Emoji, die aus zwei Emoji bestehen, sollte deren Reihenfolge egal sein.

### ISSUE THREAD

**Issue by moritzkraehe** [baeuchle/ds100bot#100]
Magic Emoji wären dadurch einfacher zu merken; zudem dürfte es eh nicht sinnvoll sein, dass die beiden selben Emoji in einer unterschiedlichen Reihenfolge eine unterschiedliche Bedeutung haben.

**Comment by baeuchle** [comment]
Nur für Frankfurt anwendbar. Eigentlich brauchen wir dafür alle vier: 🍎🚋, 🚋🍎, 🍏🚋, 🚋🍏

Um das einfacher zu machen, wäre eine Übersetzung #_FFM -> {Magic Emojis}, #_DE → {}, ... nice, aber ich weiß nicht…

**Comment by moritzkraehe** [comment]
Ob die Übersetzung sinnvoll wird, hängt denke ich davon ab, wie viele Magic Emoji im Laufe der Zeit noch hinzukommen werden...

**Comment by baeuchle** [comment]
Der Benefit einer Übersetzung MHT -> Magic Emoji wäre, dass die MHT _FFM, _NO, _DE, _HH und vlt bald _CH für mehr als eine Quelle definiert sind und ich Änderungen mit so einer Übersetzungstabelle nur an einer Stelle hätte. Der Gedanke ist allerdings eher intern zwischen mir und mir relevant 😉.
