### ISSUE TITLE
Anpassung der Linien in Frankfurt/Main zum Fahrplan 2021

### ISSUE THREAD

**Issue by moritzkraehe** [baeuchle/ds100bot#101]
Änderungen

- 25 nun zur Endstelle Nieder-Erlenbach im Fuchsloch (statt Rundfahrt durch Nieder-Erlenbach)
- 31 bis Fechenheim, Hugo-Junkers-Straße
- Linienasttausch Linie 54/M55
- Linie 61 über Gateway Gardens
- Stadtlinien 72 und 73 werden zur M72/M73, darum können Linien 72 Flughafen–Bischofsheim und Flughafen–Kelsterbach aufgenommen werden
- Neue Linie 87
- Neue Linie E12
- Metrobusse M32, M34, M36, M43, M55, M60, M72, M73
- Neue Linie X58
- Linie 58 jetzt ab "Eschborn West", nicht mehr "(Eschborn West)"
- Neue Linie X61
- Linie 77 wird zur X77
- Nachtbusnetz völlig neu. **Achtung: Groß- und Kleinschreibung ist hier jetzt relevant!** Schienennahe Nachtbusse haben ein großes N, übrig gebliebene "alte" Nachtbusse haben ein kleines n.

Außerdem Fehlerbehebungen:

- Linie 91 berührt Frankfurt nicht, sondern beginnt in Weißkirchen/Steinbach. Alle Fahrten von und nach Frankfurt haben die Nummer 251
- Linie 551 fehlte
- Linie 653 fehlte
- Linie 67 fehlte
- Linie 84 fehlte

Problem:

- Linie 56 (Friedrichsdorf) berührt neu Frankfurt, aber kollidiert mit Stadtlinie 56

Aktualisierte Liste:

[Frankfurt2021.zip](https://github.com/baeuchle/ds100bot/files/5668494/Frankfurt2021.zip)

(Bin mir nicht ganz sicher, ob ich, wenn ich, wie die Lizenz es verlangt, die Datei mit einem Hinweis auf meine Bearbeitung versehe, nicht vielleicht den Bot verwirre, daher habe ich das gelassen. Du kannst das ja dann auf der Website korrekt angeben.)

**Comment by moritzkraehe** [comment]
Für die "schienennahen Nachtbusse" habe ich den Linienverlauf der jeweiligen Schienenbahn aus der Ursprungsdatei übernommen und ggfs. leicht verändert, nicht den wesentlich weniger ausführlichen Linienverlauf, den die Traffiq angibt. Einheitlichkeit und so.

**Comment by baeuchle** [comment]
Zur Lizenz: beziehst du dich auf §4b? Ich glaube, das bezieht sich darauf, wenn du denn Code des Bots verändert weitergibst. Soweit ich das verstehe, trifft auf deine Änderung §5 zu.

**Comment by moritzkraehe** [comment]
Ah. Ja, stimmt. Dann ist eh egal.

**Comment by Jonaes** [comment]
Die 56 heißt doch ab irgendwo in Homburg HG-8, oder? Im Fahrplan selbst steht merkwürdigerweise nicht, das PDF heisst aber 56/8.  https://www.rmv.de/c/fileadmin/import/timetable/VHT_Linienfahrplan_568_13.12.20.pdf

**Comment by moritzkraehe** [comment]
Tatsache, und in der Struktur des PDF-Dokuments steht sogar auch Linie 8. Dann wäre `HG8,HG 8;Friedrichsdorf - Seulberg - Ober-Erlenbach - Nieder-Eschbach` wohl eine Lösung.

Gibt es wirklich kein Kürzel für Friedrichsdorf?

**Comment by Jonaes** [comment]
HG steht in dem Fall für den Hochtaunuskreis, denke ich, analog z.B. MKK-xx, also wäre das die HG-56.

**Comment by moritzkraehe** [comment]
Die 72 und 73 haben dann vermutlich auch irgendein Kürzel? Auf der RMV-Website steht allerdings nur 72, 73 und 56, anders als bei der OF-50, die mit Kürzel genannt ist. Weiß nicht, welcher Logik da gefolgt wird.
