### ISSUE TITLE
Buslinien Landkreis Ostprignitz-Ruppin

### ISSUE THREAD

**Issue by jonasr97** [baeuchle/ds100bot#109]
Vorschlag für neue Datenquelle:
* Art der Quelle: /Linien
* Kurzbeschreibung/Netz: Buslinien der Ostprignitz-Ruppiner Personennahverkehrsgesellschaft mbH
* Die Daten stehen unter/stelle ich unter folgende Lizenz: CC BY-SA 4.0
* Quelle: Eigene Zusammenstellung auf Basis von: www.orp-busse.de
* Vorgeschlagenes Kürzel: /ORP, /OPR

Ich habe die Regeln verstanden und bin damit einverstanden: Ja

[Linien_ORP.zip](https://github.com/baeuchle/ds100bot/files/5791540/Linien_ORP.zip)

**Comment by baeuchle** [comment]
Kannst du mir ein bisschen Kontext zur ORP geben? Sind die der einzige Anbieter im Landkreis, fahren die eigenwirtschaftlich oder eingebettet in einen Verkehrsverbund? Worein fügen sich die Liniennummern – das sieht nicht danach aus, als seien sie losgelöst von einer größeren Struktur.

Ich würde lieber diese größere Struktur aufnehmen.

**Comment by jonasr97** [comment]
Es gibt viele in andere Landkreise ausbrechende Linien der ORP, die einbrechenden Linien anderer Verkehrsunternehmen sind zu vernachlässigen. Die ORP ist im VBB organisiert und die Liniennummern passen sich dem Schema des VBB an, siehe Anhang. Da dort viele Nummern mehrfach vergeben sind, nicht nur bei den Bussen, ist es in meinen Augen keine gute Idee z.B. alle VBB-Linien als Datensatz zu haben.

![LinienVBB](https://user-images.githubusercontent.com/76997664/107741356-4ab04300-6d0d-11eb-86ed-9f6f04ffb4ca.png)

**Comment by baeuchle** [comment]
Danke.
