### ISSUE TITLE
fehlende Kursbuchstrecken

### ISSUE THREAD

**Issue by jonasr97** [baeuchle/ds100bot#114]
Einige Kursbuchstrecken haben ihrerzeits eine Nummer zugeteilt bekommen, sind aber mittlerweile nicht mehr im Kursbuch zu finden, und somit auch [hier](https://github.com/baeuchle/ds100bot/blob/github/sources/strecken_de_kbs.csv) nicht vertreten. Ich habe sie mal zusammengetragen:

[KBS.zip](https://github.com/baeuchle/ds100bot/files/6032364/KBS.zip)

**Comment by baeuchle** [comment]
Welche Quelle kann ich angeben?
