### ISSUE TITLE
ÖPNV Schwerin

### ISSUE THREAD

**Issue by jonasr97** [baeuchle/ds100bot#124]
Vorschlag für neue Datenquelle:
* Art der Quelle: /Linien
* Kurzbeschreibung/Netz: ÖPNV-Linien im Schweriner Stadtgebiet (Bus, Tram, Fähre) 
* Die Daten stehen unter/stelle ich unter folgende Lizenz: CC BY-SA 4.0
* Quelle: Eigene Zusammenstellung auf Basis von: Websites der Verkehrsunternehmen Nahverkehr Schwerin (NVS), Nahbus Westmecklenburg (NAHBUS) und Verkehrsgesellschaft Ludwigslust-Parchim (VLP)
* Vorgeschlagenes Kürzel: /SN

Ich habe die Regeln verstanden und bin damit einverstanden: Ja

[Linien_Schwerin.zip](https://github.com/baeuchle/ds100bot/files/6673064/Linien_Schwerin.zip)

**Comment by baeuchle** [comment]
Sachsen hat bereits SN.

**Comment by baeuchle** [comment]
Wie wäre es mit SWN?

**Comment by jonasr97** [comment]
Bei SWN denke ich irgendwie eher an Stadtwerke Neuruppin. Oder Neumünster, die betreiben sogar Bus. 

Vielleicht entweder VWM (Verkehrsgemeinschaft Westmecklenburg), dann fehlen allerdings die Linien in den Landkreisen, kann ich aber nachbessern, oder NVS (Nahverkehr Schwerin), weil von denen ja ein Großteil der Linien betrieben wird.

**Comment by jonasr97** [comment]
Die Lösung des Problems: die Aufteilung in die drei Verkehrsunternehmen mit allen Linien und jeweils eigenem Kürzel:

/NVS = Straßenbahn- und Buslinien der Nahverkehr Schwerin GmbH
/VLP = Buslinien der Verkehrsgesellschaft Ludwigslust-Parchim mbH
/NWM = Buslinien der NAHBUS Nordwestmecklenburg GmbH

Hier die neuen Listen:
[Linien_Schwerin.zip](https://github.com/baeuchle/ds100bot/files/6924097/Linien_Schwerin.zip)

**Comment by baeuchle** [comment]
Ich entscheide jetzt mal auf #_SCHWERIN / /SCHWERIN für alles.
