### ISSUE TITLE
Haltestellen Schwerin

### ISSUE THREAD

**Issue by jonasr97** [baeuchle/ds100bot#143]
Vorschlag für neue Datenquelle:
* Art der Quelle: #Orte
* Kurzbeschreibung/Netz: Haltestellen vom Nahverkehr Schwerin
* Link: https://www.nahverkehr-schwerin.de/de/fahrplaene.html
* Quelle: Eigene Zusammenstellung auf Basis von: Website Nahverkehr Schwerin (NVS)
* Die Daten stehen unter/stelle ich unter folgende Lizenz: CC BY-SA 4.0

Ich habe die Regeln verstanden und bin damit einverstanden: Ja

[NVS Hst.csv](https://github.com/baeuchle/ds100bot/files/8936059/NVS.Hst.csv)

**Comment by baeuchle** [comment]
Oha das erinnert an #124, den ich bisher nicht bearbeitet habe. Entschuldigung!
