### ISSUE TITLE
Bot folgt nicht auf Mastodon

### ISSUE THREAD

**Issue by f2k1de** [baeuchle/ds100bot#148]
### Mein Problem:

`@ril100@botsin.space #folgenbitte` funktioniert nicht auf Mastodon.

### Schritte die ich versucht habe:

- Dem Bot folgen
- Einen öffentlichen Toot erstellen mit dem Inhalt `@ril100@botsin.space #folgenbitte`

### Ergebnis was ich erwartet hätte:

- Der Bot folgt mir

### Was stattdessen passiert ist:

- Nichts

**Comment by baeuchle** [comment]
Nur falls das bei der Fehlerbehebung wichtig werden sollte: Request kommt aus zug.network.

**Comment by baeuchle** [comment]
Soweit ich das sehe, folgt dir der Bot jetzt. Ich glaube, die Übertragung ist einfach sehr lahm.

Ich versuche mal zu rekonstruieren:
- Gestern um 19:05 (das ist der Zeitstempel, den ich im chaos.social-Webinterface lese) hast du #folgenbitte geschickt.
- Um 19:06 fragst du nach. Dazwischen kann der Bot nichts gemacht haben, weil er nur */4 läuft, also erst um :08. (Das ist keine Kritik.)
- Um 19:20 antworte ich (ohne den 19:06-Toot von dir gelesen zu haben) ebenfalls mit #folgenbitte.
- Um 21:20 CET loggt der Bot das #folgenbitte von dir („not yet following“ aus [dieser Zeile](https://github.com/baeuchle/ds100bot/blob/main/AnswerMachine/react.py#L29))
- Um 21:48 CET loggt der Bot das #folgenbitte von mir („already following“ aus [dieser Zeile](https://github.com/baeuchle/ds100bot/blob/main/AnswerMachine/react.py#L27))

Ältere Notifications kann ich nicht sehen, deswegen kann ich die „delay-Hypothese“ nicht weiter untermauern, aber ich mach das hier trotzdem mal zu. Danke aber nochmal für die Meldung, ich bemühe mich, das im Auge zu behalten.
