### ISSUE TITLE
Changelog und PR besser handlen

### ISSUE THREAD

**Issue by baeuchle** [baeuchle/ds100bot#150]
Ich soll keine commits in Pull Requests ändern. Dazu gibt es den Anfang einer Diskussion hier: https://github.com/baeuchle/ds100bot/pull/147#issuecomment-1309250156, die ich gerne hierhin verlagern will.

**Comment by baeuchle** [comment]
Aaalso. Der Code ist im Submodul GitVersion, hier: https://github.com/baeuchle/gitversion/blob/ea18d1977ce72780c8100d06c747539ad8566ce9/__init__.py#L39
Das macht im Prinzip eine Python-Variante von
$ git log OLD_VERSION..HEAD | grep '^CHANGELOG ' | sed 's/CHANGELOG /•/' und sollte auch merge commits sehen (oder wie auch immer sed funktioniert)

Ich lasse über die fertigen Commits dann tools/add_score_to_commit drüberlaufen. Ich könnte die zu postenden CHANGELOGs auch in den jeweiligen tag ablegen, aber dazu bin ich noch nicht gekommen. Ich könnte auch mal ein ordentliches CI hier auf github einrichten, aber dazu bin ich auch noch nicht gekommen.

Bisher gab es nicht nur 25 Pull Requests, da würde ich mir die history also nicht mit übermäßig vielen empty commits zumüllen. Dass es überhaupt ein Problem ist, wenn ich die Commits noch bearbeite, war mir aber bisher noch überhaupt nicht bewusst! You live, you learn. Manche PR waren faulty, vor allem wegen ByteOrderMarks am Anfang von CSV-Dateien.

Das mit der Rückkopplung ist ein Problem: manche PR liegen lange rum, bis ich endlich dazu komme, mich darum zu kümmern. Und dieser Termin ist auch nicht immer gut vorhersagbar: dann sitze ich also endlich mal einen Abend am Bot, mache dann total triviale (or so I would think) Änderungswünsche und kann an dem Abend nicht weitermachen, weil ich auf deren Erledigung warten muss. Irgendwie unbefriedigend.

**Comment by baeuchle** [comment]
cc @autinerd und @9Lukas5 .

**Comment by 9Lukas5** [comment]
Also ich hab mal kurz bisschen getestet :nerd_face: 

__Annahmen:__

- Da wo du den Bot ausführst, ist direkt das Git-Repo geklont
- Du rufst das Bot-Hauptprogramm (`ds100bot`) auf
- Danach folgt das ganze folgender Aufruf-Kette:
    - https://github.com/baeuchle/ds100bot/blob/728f465ba50a56a97942ddd2953e14fb5307713a/ds100bot#L37
    - https://github.com/baeuchle/ds100bot/blob/728f465ba50a56a97942ddd2953e14fb5307713a/Persistence/__init__.py#L5
    - https://github.com/baeuchle/ds100bot/blob/728f465ba50a56a97942ddd2953e14fb5307713a/Persistence/gitdescribe.py#L60
    - https://github.com/baeuchle/ds100bot/blob/728f465ba50a56a97942ddd2953e14fb5307713a/Persistence/gitdescribe.py#L52
    - https://github.com/baeuchle/gitversion/blob/ea18d1977ce72780c8100d06c747539ad8566ce9/__init__.py#L43
        ```python
        for line in self._gitlines('log', '{}..HEAD'.format(old_version)):
        ```
- Du startest den Bot immer nur auf Tags, womit das `git describe`  eine auffindbare Referenz liefert
- Die letzte Referenz auf der du den Bot gestartet hast liegt in der Datenbank, was als Ausgangspunkt für den neuen Changelog übergeben wird

__Testergebnisse:__

Ich hab auf meinem Fork mal schnell paar Feature Branches gemacht und mit den Commits, Merges und dem Pull-Request Feature auf GitHub gespielt und nur die Changelog-generierende Logik in ner interaktiven Python-Shell probiert.  
Wie vermutet filtert dein `git log` Aufruf Merge-Commits nicht aus, eine `CHANGELOG` Zeile in der Commit-Message eines Merge-Commits wird also ebenso erfasst.

__Vorschlag:__

Wenn du einen PR über das GitHub WebGUI annimmst bekommt man ja die Commit-Message gezeigt die der Merge-Commit bekommt.
Du könntest also die CHANGELOG Zeile(n) und Ergebnisse der Tests in die Message des Merge-Commits hinzufügen und die _sollten_ von deinem Parser im aktuellen Zustand bereits ebenfalls erfasst werden.

**Comment by 9Lukas5** [comment]
Wenn du es einfach mal testen willst, ich könnte folgende Änderung anbieten, damit ich beim Commit nicht aufpassen mit die auszulassen :zany_face: 

```diff
diff --git a/.gitignore b/.gitignore
index 2e7a5c3..5bb4042 100644
--- a/.gitignore
+++ b/.gitignore
@@ -8,3 +8,13 @@ doc/dumps.snip
 tweet_details.py
 saved_tweets/
 sonstiges/
+
+# Python Virt-Env
+env/
+
+# VSCode/VSCodium
+.vscode/
+
+# IntelliJ
+.idea/
+*.iml
```

Ich mach einfach mal nen PR^^

**Comment by 9Lukas5** [comment]
Das andere Anliegen von @autinerd, zusätzlich auch eine `CHANGELOG.md` für die Entwickler zu führen, würde ich an den Schritt in deinem Workflow koppeln, wo du einen neuen Tag setzt. Da wäre halt nur noch die Frage der Umsetzung.

Ich benutz bei meinen Sachen ganz gern [commit-and-tag-version](https://github.com/absolute-version/commit-and-tag-version), was aber bedingt, dass die Commit-Messages dem [Conventional Commits](https://www.conventionalcommits.org) Standard folgen, um vom Parser erfasst und in eine Markdown formatierte `CHANGELOG.md` geschrieben zu werden.    
Auch hier kann ein Merge-Commit genutzt werden, die Nachricht die im Changelog landet ist aber halt immer die Commit-Titelzeile.

Alternativ könnte man den Python-Code erweitern, und die gleichen geparsten Zeilen wie für den Nutzer-Changelog auch in den Entwickler-Changelog im Repo schreiben.
Da kommts jetzt auf deine Präferenz an, was du machen willst^^

**Comment by 9Lukas5** [comment]
> Da steckt die weitere Annahme drin, dass ich grafische Oberflächen weniger stark meide als der Teufel Weihwasser.

Naja, ich hab zuerst auf'm Terminal lokal getestet, weil das ist häufig der Ort wo ich sachen mach, aber ich hab mich halt mittlerweile schon so oft mit Studienkollegen rumschlagen müssen beim Thema Git, dass ich im Kopf hab das die Mehrheit alles mit GUIs machen will :roll_eyes:   
Deshalb wollt ich sicherstellen, dass es mit beiden Wegen geht :ok_hand: 

> brr javascript. Muss jetzt eher nicht

Ja gut :see_no_evil:   
Hab gedanklich schon mal mit nem eigenen Python Progämmchen gespielt, dass conventional-commits parst.
Aber ist halt arbeit :grimacing: 

> Der Changelog des Bots ist ja nicht für Entwickler gedacht, sondern für das Soziale Netzwerk.

Klar, das schon.
Aber so generell wäre halt auch einer der im Repo liegt nicht schlecht für die Codebasis/Entwickler :shrug: :laughing: 
Nur manuell schreiben wollen würd ich den auch nicht, deshalb ja conventional-commits + tool :sunglasses:

**Comment by baeuchle** [comment]
Ich korrigiere mich noch:

`git log --decorate --pretty=%D%n%b | grep -e '^CHANGELOG \|^tag' | sed 's/CHANGELOG //' | sed 's/^tag: /== /' > CHANGELOG.md`

**Comment by baeuchle** [comment]
> > Der Changelog des Bots ist ja nicht für Entwickler gedacht, sondern für das Soziale Netzwerk.
> 
> Klar, das schon. Aber so generell wäre halt auch einer der im Repo liegt nicht schlecht für die Codebasis/Entwickler shrug laughing Nur manuell schreiben wollen würd ich den auch nicht, deshalb ja conventional-commits + tool sunglasses

Da sind wir nun aber bei einem feature request: „mach mal ein developer's change log“ und nicht mehr bei „handle mal dein SocialMedia-changelog besser“. Und das ist dann ja nochmal ein ganz anderes Paar Schuhe.

**Comment by 9Lukas5** [comment]
Da hast du recht 😄
Sorry @autinerd 🙃

Also wenn das damit funktioniert es in den Merge Commit zu schreiben und sonst keiner Einwände oder andere Vorschläge dazu hat, wär das Thema ja dann theoretisch schon geklärt oder?^^

Höchstens noch bisschen Zeit lassen, falls noch jemand was dazu beitragen will, aber sonst 🤷🏼👍🏼

**Comment by baeuchle** [comment]
Die Person kann ja zur Not wiedereröffnen.
