### ISSUE TITLE
SPNV-Niedersachsen

### ISSUE THREAD

**Issue by simonbredemeier** [baeuchle/ds100bot#19]

**Comment by simonbredemeier** [comment]
[Niedersachsen.zip](https://github.com/baeuchle/ds100bot/files/4891548/Niedersachsen.zip)

**Comment by baeuchle** [comment]
Unter welche Lizenz stellst du diese Daten? Siehe https://ds100.frankfurtium.de/copyright.html

**Comment by simonbredemeier** [comment]
CC0
