### ISSUE TITLE
ÖPNV VBB

### ISSUE THREAD

**Issue by Freddy1404** [baeuchle/ds100bot#20]
Based on the dataset from [https://www.vbb.de/unsere-themen/vbbdigital/api-entwicklerinfos/datensaetze](https://www.vbb.de/unsere-themen/vbbdigital/api-entwicklerinfos/datensaetze) I can provide routes for VBB (zones ABC)

**Comment by Freddy1404** [comment]
Single direction; VBB ferries, busses, trams and trains with agencies

[vbb_ds100.zip](https://github.com/baeuchle/ds100bot/files/4891863/vbb_ds100.zip)

**Comment by baeuchle** [comment]
Unter welche Lizenz stellst du diese Daten? Siehe https://ds100.frankfurtium.de/copyright.html

**Comment by Freddy1404** [comment]
Da die direkte Quelle [VBB-GTFS](https://www.vbb.de/unsere-themen/vbbdigital/api-entwicklerinfos/datensaetze) unter CC BY 4.0 ist, würde ich dies auch tun, da ich die Daten nur zusammengestellt habe (Script [https://github.com/Freddy1404/gtfs_to_sqlite](https://github.com/Freddy1404/gtfs_to_sqlite)). Eine Nennung würde mich freuen (Twitter @_f14h)

**Comment by Freddy1404** [comment]
Ich habe hier nochmal die Daten nur auf S-Bahn, U-Bahn und Regio reduziert, sowie die Bahnhofsnamen etwas schöner gemacht (wie "Bahnhof " rausgenommen, S+U rausgenommen, ", Berlin" raus, usw.)


[vbb_ds100_rail.zip](https://github.com/baeuchle/ds100bot/files/4901529/vbb_ds100_rail.zip)

**Comment by baeuchle** [comment]
Hi, die Datensätze sind zu lang, das kann ich so nicht importieren. (Jeder einzelne sollte nicht länger als ein Tweet sein, das bedeutet etwa 275 Zeichen Kurz + Lang.) Kann ich selbst kürzen, aber ich habe keine Ortskenntnis.

**Comment by Freddy1404** [comment]
Hm, das wird schwierig IMHO, bei Routen wie `Rathaus Spandau - Altstadt Spandau - Zitadelle - Haselhorst - Paulsternstr. - Rohrdamm - Siemensdamm - Halemweg - Jakob-Kaiser-Platz - Jungfernheide - Mierendorffplatz - Richard-Wagner-Platz - Bismarckstr. - Wilmersdorfer Str. - Adenauerplatz - Konstanzer Str. - Fehrbelliner Platz - Blissestr. - Berliner Str. - Bayerischer Platz - Eisenacher Str. - Kleistpark - Yorckstr. - Möckernbrücke - Mehringdamm - Gneisenaustr. - Südstern - Hermannplatz - Rathaus Neukölln - Karl-Marx-Str. - Neukölln  - Grenzallee - Blaschkoallee - Parchimer Allee - Britz-Süd - Johannisthaler Chaussee - Lipschitzallee - Wutzkyallee - Zwickauer Damm - Rudow` (634 Zeichen) oder `Brandenburg, Hbf - Götz - Groß Kreutz - Werder - Pdm, Park Sanssouci - Pdm, Charlottenhof - Pdm Hbf - Wannsee - Charlottenburg - Bhf Zoo - Bln Hbf - Friedrichstr. - Alexanderplatz - Ostbahnhof - Ostkreuz - Erkner - Grünheide, Fangschleuse - Hangelsberg - Fürstenwalde - Frankfurt - Brieskow-Finkenheerd, Kraftwerk Finkenheerd - Brieskow-Finkenheerd, Finkenheerd - Wiesenau - Ziltendorf - Eisenhüttenstadt - Neuzelle - Wellmitz - Coschen - Guben - Kerkwitz - Jänschwalde, Ost - Jänschwalde - Peitz, Ost - Teichland - Cottbus, Willmersdorf Nord - Cottbus, Merzdorf - Cottbus, Sandow - Cottbus, Hbf
` (595 Zeichen) diese so drastisch abzukürzen, dass sie immer noch Sinne ergeben.

**Comment by baeuchle** [comment]
Ich kenne mich, wie gesagt, nicht aus, aber es muss ja nicht jeder Zwischenhalt aufgeführt werden, um zu verstehen, wo die Linie entlangfährt. In deinem zweiten Beispiel fällt mir spontan auf, dass man "Pdm Hbf - Wannsee - Charlottenburg - Bhf Zoo - Bln Hbf - Friedrichstr. - Alexanderplatz - Ostbahnhof - Ostkreuz" wsl mit "Potsdam - Berlin Stadtbahn - Ostkreuz" oder eventuell auch "Potsdam - Berlin Hbf - Berlin Ostbahnhof - Erkner - Frankfurt (Oder) - ..." abkürzen könnte. (Wie gesagt, ohne Ortskenntnis – vielleicht entgeht mir da was.)

**Comment by jonasr97** [comment]
Viele Linienbezeichnungen im VBB sind leider doppelt vergeben, insbesondere die Buslinien. Daher macht es in meinen Augen keinen Sinn, alle Linien im VBB als Datensatz zu haben, sondern z.B. Buslinien nach Landkreisen zu sortieren. Da dürften sich die eigentlich nicht doppeln...
