### ISSUE TITLE
SPNV Thüringen (TH)

### ISSUE THREAD

**Issue by Jonaes** [baeuchle/ds100bot#24]
Ich hab mal die EVU hinten drangehangen. Könnte IMO auch interessant sein. (Ja, da wo Linienbezeichnung=EVU ist das eher witzlos)

Das sind erstmal nur stumpf die Strecken, wer Linienbezeichnungen kennt, darf die natürlich gerne dranhängen :).

Fehler im csv-Format möge man mir bitte verzeihen.

[Datei](https://github.com/baeuchle/ds100bot/files/4891505/DS100-Bot_TH.zip) (als zip, csv will er nicht)

**Comment by simonbredemeier** [comment]
Eine Übersicht über die Thüringer SPNV-Linien ist bei der Wikipedia unter https://de.wikipedia.org/wiki/Liste_der_Eisenbahnlinien_in_Th%C3%BCringen zu finden.

**Comment by baeuchle** [comment]
Unter welche Lizenz stellst du deine Daten? Siehe https://ds100.frankfurtium.de/copyright.html

**Comment by Jonaes** [comment]
CC-0

**Comment by Jonaes** [comment]
geupdatete Version mit Überschriften.
[DS100-Bot_TH.txt](https://github.com/baeuchle/ds100bot/files/4911070/DS100-Bot_TH.txt)
Die Zusammenstellung basiert auf einer [Übersicht des Thüringer Landesamtes für Bau & Verkehr](https://www.thueringen.de/mam/th9/tlbv/SPNV/liniennetzplan_th_ab_15.12.19.pdf)

**Comment by baeuchle** [comment]
Hi, der Link ist tot. (Habe ich da zu lange gewartet?)

**Comment by Jonaes** [comment]
Vermutlich. Hatte das ja direkt über Github hochgeladen.

Sobald ich Zuhause bin lade ichs nochmal hoch.
