### ISSUE TITLE
Bahnhofsnummern

### ISSUE THREAD

**Issue by baeuchle** [baeuchle/ds100bot#27]
Liste bei https://michaeldittrich.de/ibnr/ (?)

**Comment by dodomedia** [comment]
Du kannst die Daten entweder über die offizielle API (https://developer.deutschebahn.com/store/apis/info?name=Betriebsstellen&version=v1&provider=DBOpenData) abfragen oder die bereit gestellten CSV-Dateien dafür nutzen (je nachdem welche Infos du hier benutzen möchtest):
- https://data.deutschebahn.com/dataset/data-stationsdaten
- https://data.deutschebahn.com/dataset/data-haltestellen
