### ISSUE TITLE
Kursbuchstrecken Deutschland

### ISSUE THREAD

**Issue by baeuchle** [baeuchle/ds100bot#29]
Mögliche Quellen: https://www.bahnseite.de/purespace/Strn2001.html https://www.zugfinder.de/kbs_hinweise.php

**Comment by floflo8** [comment]
http://kursbuch.bahn.de/hafas/kbview.exe/dn?rt=1&dosearch=1&searchmode=tableplus&table_nr=%20&controlpattern=P.ddd&mainframe=utable&tocinfo=reg_tab
