### ISSUE TITLE
S-Bahnen und Zuglinien RMV

### ISSUE THREAD

**Issue by baeuchle** [baeuchle/ds100bot#31]

**Comment by Jonaes** [comment]
Hab mal angefangen.
[DS100-Bot_RMV_1-13.txt](https://github.com/baeuchle/ds100bot/files/4901534/DS100-Bot_RMV_1-13.txt)

**Comment by Jonaes** [comment]
Feddisch. Bei der S6 (sowohl die "echte" RMV-S6, als auch die VRN-S6 berühren den RMV) habe ich mal einen Eintrag mit zwei Linienläufen mit Zeilenumbruch dazwischen gemacht. Keine Ahnung ob das geht, oder ob der Bot oder Twitter dann in die Luft fliegen.
[linien_rmv.csv.txt](https://github.com/baeuchle/ds100bot/files/5000212/linien_rmv.csv.txt)
[linien_rmv.json.txt](https://github.com/baeuchle/ds100bot/files/5000213/linien_rmv.json.txt)

**Comment by baeuchle** [comment]
Super! Für einen Zeilenumbruch einfach \n nehmen; so geht das beim Import schief. Aber die VRN-S6 werde ich eh rausschmeißen; das finde ich doch etwas albern als Teil der RMV-Linien.
