### ISSUE TITLE
Bremer Straßenbahn AG, VAG Freiburg, DELBus, BremerhavenBus, ggf. VBN, Tarifverbünde Südbaden

### ISSUE THREAD

**Issue by floflo8** [baeuchle/ds100bot#39]
Ich mache mich mal an die oben genannten Dinge. Mal sehen was da so zusammenkommt ;)

**Comment by floflo8** [comment]
Hier schonmal die erste Liste für die Bremer Straßenbahn AG (BSAG). Enthalten sind alle aktuellen Linien, diverse E-Linien (Schülerverkehr, vereinfachte Einsetzer/Aussetzer) und, sofern die Nummer aktuell nicht vergeben ist, auch ehemalige Linien (als kleines Gimmick) mit eventuellen Hinweis auf heutige Linie. Durch viele verschiedene Fahrmöglichkeiten zwischen einigen Haltestellen und langen Laufwegen, sind die Lauftexte teils recht lang geworden (gerade Bremen-Nord die 90er-Linien, die Durchmesserlinien 20er-Linien und die Nachtlinien). Ich habe aber versucht, sie so allgemein wie möglich zu halten, sodass aber trotzdem noch irgendwie der Linienweg ersichtlich ist :)
[BSAG_Linien.txt](https://github.com/baeuchle/ds100bot/files/4896907/BSAG_Linien.txt)

**Comment by floflo8** [comment]
Und weiter geht's mit der sehr überschaubaren Liste der Freiburger VAG. Enthält auch nur die Linien, die die VAG selbst betreibt (sprich Stadtverkehr Freiburg). Der Rest wäre dann Bestandteil einer Liste des RVF.
[VAG_Linien.txt](https://github.com/baeuchle/ds100bot/files/4897607/VAG_Linien.txt)

**Comment by baeuchle** [comment]
Habe das Issue mal aufgeteilt in eines pro Liste. So ist es leichter 1.) für mich zum abarbeiten und 2.) für andere zu sehen, wofür es schon issues gibt.

**Comment by baeuchle** [comment]
Unter welche Lizenz stellst du diese Listen? Siehe https://ds100.frankfurtium.de/copyright.html

**Comment by floflo8** [comment]
Kann unter CC-BY-SA 4.0 stehen.

**Comment by baeuchle** [comment]
Wer bist du nochmal auf Twitter? Frage für ein befreundetes Changelog.

**Comment by floflo8** [comment]
@FloEllebrecht

**Comment by floflo8** [comment]
Moin, ich habe die seit Ende letzten Jahres verkehrende Schnellbus-Linie 63S hinzugefügt.

[BSAG_Linien.txt](https://github.com/baeuchle/ds100bot/files/6152421/BSAG_Linien.txt)
