### ISSUE TITLE
VAG Freiburg

### ISSUE THREAD

**Issue by baeuchle** [baeuchle/ds100bot#43]
Liste in #39 verlinkt.

(Ich möchte zum einfacheren Abarbeiten gerne ein Issue pro Liste haben.)

**Comment by floflo8** [comment]
Moin, ich habe die Datei mal um den gesamten RVF erweitert. Enthalten sind auch dort die Nachtlinien der SBG und Stadtverkehre der Orte, wobei denen teilweise ein Präfix (z.B. EM für Emmendingen) vorangestellt werden musste, damit es unterscheidbar zu den Linien der VAG in Freiburg selbst ist.

[RVF_Linien.txt](https://github.com/baeuchle/ds100bot/files/4980851/RVF_Linien.txt)
