### ISSUE TITLE
DELBus

### ISSUE THREAD

**Issue by baeuchle** [baeuchle/ds100bot#44]
Aus #39. Ein Issue pro Liste.

**Comment by floflo8** [comment]
Und hier kommt die Übersicht für das Haupt- und Nebennetz von Delbus (Stadtverkehr Delmenhorst). Lizenz wie auch für Freiburg und Bremen.
[Delbus_Linien.txt](https://github.com/baeuchle/ds100bot/files/4901884/Delbus_Linien.txt)
