### ISSUE TITLE
BremerhavenBus

### ISSUE THREAD

**Issue by baeuchle** [baeuchle/ds100bot#45]
Aus #39

**Comment by floflo8** [comment]
Und hier das Netz (Tageslinien, Nachtlinien, Schulverkehr) von Bremerhavenbus aus Bremerhaven. Lizenz wie bei den anderen auch schon:
[BHVBus_Linien.txt](https://github.com/baeuchle/ds100bot/files/4902087/BHVBus_Linien.txt)

**Comment by baeuchle** [comment]
Sind die Nummernschemata von Bremen, Bremerhaven und Delmenhorst kompatibel? Also: sind sie aus Zufall aktuell kompatibel oder werden sie auch kompatibel entwickelt?
