### ISSUE TITLE
SPNV Sachsen

### ISSUE THREAD

**Issue by simonbredemeier** [baeuchle/ds100bot#48]

**Comment by moritzkraehe** [comment]
Zahlreiche Liniennummern kommen in Sachsen doppelt vor, z.B.

RE19 (MRB) Dresden - Heidenau - Altenberg
RE19 (ABR) Halle - Röblingen am See - Eisleben - Sangerhausen - Leinefelde

S1, S2, S3 (Leipzig) vs. S1, S2, S3 (Dresden) etc.

Sinnvollerweise betrachten wir wohl jeden Verbund als eigenes Verkehrsnetz.
Eine Liste für den SPNV im VVO hätte ich fertig, sofern gewünscht.

**Comment by simonbredemeier** [comment]
Die Strecke Halle – Leinefelde verläuft garnicht durch Sachsen.

Größere Überschneidungen dürfte es tatsächlich nur bei den S-Bahnen geben.

**Comment by moritzkraehe** [comment]
Ach, ich hatte nicht beachtet, dass der MDV nicht nur Sachsen umfasst.
Die einzigen Konflikte sind die S-Bahn und der RE1, den gibt es tatsächlich (Göttingen--Glauchau; Dresden--Görlitz) zweimal.
Für die S-Bahn würde ich folgende Lösung vorschlagen:
![Anmerkung 2020-08-02 141451](https://user-images.githubusercontent.com/68034094/89122838-f230fb00-d4ca-11ea-8b1e-83b8b33074c6.jpg)

**Comment by simonbredemeier** [comment]
das wäre ein brauchbarer Ansatz

den RE 1 würde ich einfach Thüringen zuordnen, da der innersächsische Abschnitt sehr kurz ist

**Comment by moritzkraehe** [comment]
Das könnte man beim RE1 guten Gewissens so machen, denke ich. Was sagst du dazu, @baeuchle?

**Comment by baeuchle** [comment]
RE1 sehe ich genau so, aber ich finde diese Konstruktionen mit den S-Bahnen sinnfrei. Es gibt offensichtlich zwei S-Bahn-Netze, die sollten dann auch getrennt voneinander sein. Etwa /SMD und /SDD („S-Bahn Mitteldeutschland“ und „S-Bahn Dresden”). Und Linien /SN sind dann halt Regionalbahnlinien in Sachsen.

**Comment by moritzkraehe** [comment]
In dem Fall würde ich eher die S-Bahn Mitteldeutschland in /L für den Leipziger Nahverkehr und die S-Bahn Dresden in /DD für den in Dresden integrieren, statt jeweils eigene Datensätze zu schaffen.

**Comment by baeuchle** [comment]
Das wäre auch okay. (Bin mir nicht sicher: ist es das Leipziger s-Bahn-Netz oder ist es Halle/Leipzig? Wäre trotzdem in Ordnung.)

Letztlich soll der Bot keine Enzyklopädie sein, sondern den Text „ich bin gerade in der Dresdener S4“ einfacher schreibbar machen, und niemand würde (glaube ich) „ich bin gerade in der sächsischen S4“ sagen — VOR ALLEM, weil es uneindeutig ist. (Ich weiß, dass /RMV:S4 da nicht ganz reinpasst, aber „ich bin in der S4 von RMV“ halte ich doch noch für sinnvoller als das mit Sachsen.)

**Comment by moritzkraehe** [comment]
Moin @baeuchle, ich hätte hier "schon" mal die sächsischen Eisenbahnlinien und den Stadtverkehr Dresden. Stadtverkehre Leipzig und Chemnitz folgen bald.

[Dresden_Sachsen.zip](https://github.com/baeuchle/ds100bot/files/5249334/Dresden_Sachsen.zip)

**Comment by baeuchle** [comment]
Hi, danke! Kannst du beim Export aus der Tabellenkalkulation die Leerzeilen entfernen?

**Comment by moritzkraehe** [comment]
So, jetzt aber:
- Sachsen: SPNV außer Chemnitzbahn und S-Bahn; Elbfähren
- Dresden: Tram, Stadtbusse, Regionalbusse, S-Bahn Dresden, Elbfähren innerhalb Dresdens, Bergbahnen
- Chemnitz: Chemnitzbahn, Tram, Stadtbusse, Regionalbusse
- Leipzig: S-Bahn Mitteldeutschland, Tram, Stadtbusse, Regionalbusse
[DS100 Sachsen.zip](https://github.com/baeuchle/ds100bot/files/5361137/DS100.Sachsen.zip)

**Comment by moritzkraehe** [comment]
Hätte eigentlich gerne noch die PlusBusse aufgenommen, aber da gibt es zu viele doppelte Liniennummern über die Verkehrsverbünde hinweg.

**Comment by baeuchle** [comment]
War glaube ich hierdurch: https://twitter.com/_ds_100/status/1333495021471997960 bzw hierdurch: https://github.com/baeuchle/ds100bot/commit/fcc69e084476b5b8e12aab9eb3c398ba53553ac1 erledigt.
