### ISSUE TITLE
Buslinien Hochtaunuskreis /HG:

### ISSUE THREAD

**Issue by Jonaes** [baeuchle/ds100bot#84]
Vorschlag für neue Datenquelle:
* Art der Quelle (#Orte, $Strecken, %Signale, &Regeln_Sonstiges, /Linien, Typen): /Linien
* Kurzbeschreibung/Netz (z.B. „Niederländische Signalordnung“, „Japanische Linien“): Buslinien Hochtaunuskreis (+ die 2 U-Bahn-Linien) 
* Link: https://www.rmv.de/c/de/fahrplanauskunft/fahrplaene/linienfahrplaene/fahrplantabellen?tx_ikanosrgfilter_regionalfilter%5Baction%5D=list&tx_ikanosrgfilter_regionalfilter%5Bcontroller%5D=Region&use_session=1&cHash=eead31bbb9542f5c2dc43ad2f9f3b937#results

https://www.bad-homburg.de/leben-in-bad-homburg/mobilitaet-verkehr/bus-bahn/Busse.php#c1
* Ich möchte selbst daran arbeiten (Ja/Nein)*: Ja
* Die Daten stehen unter/stelle ich unter folgende Lizenz**: CC0
* Vorgeschlagenes Kürzel (z.B. 'CH') und Magic Hashtag (z.B. '\_CH'): HG/_HG

## Hinweise für Liniennetze:
- Daten sollten nach Liniennetzen sortiert sein – also etwa nach Verkehrsverbünden oder S-Bahn-Netzen.
- Soll ein Datensatz in verschiedenen Liniennetzen auftauchen, sollte der Text dafür identisch sein.
- Der Langtext sollte eine sinnvolle Identifizierung des Linienweges zulassen: Unterwegshaltepunkte sind erlaubt, sollten aber nicht überhand nehmen. Siehe unten zur Länge der Texte.
- Hat eine Linie unterschiedliche Laufwege, sollten diese sinnvoll dargestellt werden.
- Keine zwei Einträge für Hin- und Rückrichtung.

## Hinweise für die Bearbeitung:
Bitte die Dokumentation für [Konfigurationen](https://ds100.frankfurtium.de/data.html) und  [Datenlisten](https://ds100.frankfurtium.de/sources.html) beachten.

Ich habe die Regeln verstanden und bin damit einverstanden: ✅

**Comment by Jonaes** [comment]
Tadaaa. (Boah ey, könnt ihr keine einfachen Linienläufe planen...)
[linien_hg.csv.txt](https://github.com/baeuchle/ds100bot/files/5063261/linien_hg.csv.txt)
[linien_hg.json.txt](https://github.com/baeuchle/ds100bot/files/5063262/linien_hg.json.txt)

**Comment by Jonaes** [comment]
[linien_hg.csv.txt](https://github.com/baeuchle/ds100bot/files/5063335/linien_hg.csv.txt)
[linien_hg.json.txt](https://github.com/baeuchle/ds100bot/files/5063336/linien_hg.json.txt)
So, jetzt aber. Warum auch immer die Fahrpläne von Friedrichsdorf nicht mit beim VHT liegen...

**Comment by baeuchle** [comment]
Fixed in 73c3bc9a3d2521ef5c4083068771716923c96061
