### ISSUE TITLE
Betriebsstellen Schweden

### ISSUE THREAD

**Issue by floflo8** [baeuchle/ds100bot#89]
Vorschlag für neue Datenquelle:
* Art der Quelle (#Orte, $Strecken, %Signale, &Regeln_Sonstiges, /Linien, Typen): Betriebsstellen
* Kurzbeschreibung/Netz (z.B. „Niederländische Signalordnung“, „Japanische Linien“): Schwedische Betriebsstellen
* Ich möchte selbst daran arbeiten (Ja/Nein)*: Ja
* Die Daten stehen unter/stelle ich unter folgende Lizenz**: wie alles andere von mir auch
* Vorgeschlagenes Kürzel (z.B. 'CH') und Magic Hashtag (z.B. '\_CH'): SE

## Hinweise für Liniennetze:
- Daten sollten nach Liniennetzen sortiert sein – also etwa nach Verkehrsverbünden oder S-Bahn-Netzen.
- Soll ein Datensatz in verschiedenen Liniennetzen auftauchen, sollte der Text dafür identisch sein.
- Der Langtext sollte eine sinnvolle Identifizierung des Linienweges zulassen: Unterwegshaltepunkte sind erlaubt, sollten aber nicht überhand nehmen. Siehe unten zur Länge der Texte.
- Hat eine Linie unterschiedliche Laufwege, sollten diese sinnvoll dargestellt werden.
- Keine zwei Einträge für Hin- und Rückrichtung.

## Hinweise für die Bearbeitung:
Bitte die Dokumentation für [Konfigurationen](https://ds100.frankfurtium.de/data.html) und  [Datenlisten](https://ds100.frankfurtium.de/sources.html) beachten.

Ich habe die Regeln verstanden und bin damit einverstanden: Jepp

**Comment by floflo8** [comment]
[Betriebsstellen_Schweden.txt](https://github.com/baeuchle/ds100bot/files/5241788/Betriebsstellen_Schweden.txt)

Dies sind alle Betriebsstellen des schwedischen Stammnetzes, sowie der Inlandsbanan und des Arlanda Express. Andere Strecken (Schmalspur etc.) haben teils gleiche Kürzel wie das Stammnetz aber für andere Stationen, sodass ich diese komplett ausgenommen habe.

**Comment by baeuchle** [comment]
Hi, was kann ich denn als Quelle angeben? Private Communication? Oder gibt's die Liste auch irgendwo öffentlich?

**Comment by floflo8** [comment]
Es gibt ein PDF dazu, dass ich aber nicht vernünftig kopieren konnte. Also habe ich die Liste bei Wikipedia kopiert: https://sv.m.wikipedia.org/wiki/Lista_%C3%B6ver_trafikplatssignaturer_i_det_svenska_j%C3%A4rnv%C3%A4gsn%C3%A4tet
