### ISSUE TITLE
Landesflagge als Moduswechsel

### ISSUE THREAD

**Issue by Zugschlus** [baeuchle/ds100bot#94]
Hi,

mit #_CH kann ich zum Beispiel den Modus wechseln, damit Bahnhofskürzel aus einem anderen Land ohne Prefix übersetzt werden. Das könnte man auch mit Landesflaggen machen.

🍔 für #HOCHBAHN oder 🧸 für #BVG wäre vielleicht etwas übertrieben ;-)

Grüße
Marc

**Comment by baeuchle** [comment]
Ist mir grade ein bisschen zu kompliziert.

For future me:
- AnswerMachine.tweet.hashtags() muss die Flaggen auch finden; dafür muss das Argument candidate_list diese auch enthalten. Hier braucht es aber dann ein bisschen mehr Code als aktuell, weil wir nicht mehr die vorgefundenen Twitter-Hashtags finden können. Ein Nebeneffekt könnte aber sein, dass MHT auch im ALT-Text die Quelle umstellen können.
- Externals.database.magic_hashtags müsste diese dann auch (nur im zweiten Rückgabewert!) ausgeben.
Beides sollte keine anderen Nebeneffekte haben (nur # + Flagge würde auch als "hat MHT" gewertet).
