### ISSUE TITLE
Schweizer/SBB-Strecken

### ISSUE THREAD

**Issue by baeuchle** [baeuchle/ds100bot#99]
Vorschlag für neue Datenquelle:
* Art der Quelle: $
* Kurzbeschreibung/Netz: Schweizer (oder SBB-)Strecken
* Link: https://t.co/tsWxMTLvWN
* Die Daten stehen unter/stelle ich unter folgende Lizenz**: noch nicht geklärt
* Vorgeschlagenes Kürzel (z.B. 'CH') und Magic Hashtag (z.B. '\_CH'): $CH/#_CH

**Comment by steschny** [comment]
Weitere offizieller Wikipedia Link

https://de.m.wikipedia.org/wiki/Liste_der_bestehenden_Schweizer_Eisenbahnstrecken

**Comment by steschny** [comment]
Offizielles Kursbuch Schweiz:

https://www.fahrplanfelder.ch/de/archiv/grafische-fahrplaene.html

**Comment by steschny** [comment]
Open Data csv Link:

https://opendata.swiss/de/dataset/linie/resource/1159850c-1df2-46b2-9dea-01657aca437a

**Comment by baeuchle** [comment]
Ach cool, das CSV hatte ich noch nicht gefunden. Top!
